services:
  logs-action-group:
    container_name: logs_action_group
    build:
      dockerfile: ./Dockerfile
      context: ./
    ports:
      - 3000:80
    environment:
      - AWS_DEFAULT_REGION=us-west-2
      - API_SECRET_NAME=grafana_logs_auth_key_pair